name: "🐞 Bug Report"
description: "Let us know about a bug so we can fix it."
title: "[BUG] <title>"
labels: ["bug", "unverified"]

body:

  - type: markdown
    id: introduction
    attributes:
      value: "Thank you for taking the time to report this issue. Before you submit this we ask you make a reasonable effort to check if someone else has already submitted the same issue. Additionally, please keep in mind that this project is provided for free and any support you receive is offered by volunteers. It may take a few days or even weeks to receive a response. Support may be denied if you are being rude, impatient, or demanding."

  - type: input
    id: mod_version
    attributes:
      label: "Mod Version"
      description: "What version of the mod are you using?"
      placeholder: "Example: 1.0.2"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Are you playing on a dedicated server?"
      options:
        - "Yes"
        - "No"
        - "LAN"
        - "Don't Know"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "Issue Description"
      description: "Please describe the issue you are experiencing the best you can."
    validations:
      required: true
