name: "⭐ Feedback"
description: "Share an idea for a new feature or change to existing content."
title: "[FEEDBACK] <title>"
labels: ["feedback"]

body:

  - type: markdown
    id: introduction
    attributes:
      value: "Thank you for taking the time to share your feedback with us. While we do appreciate your feedback please keep in mind that not all feedback can be implemented. This project is provided for free by volunteers, responses will not be immediate."

  - type: textarea
    id: feedback_description
    attributes:
      label: "Feedback"
      description: "What is your feedback for the project?"
    validations:
      required: true
