name: "❓ Question"
description: "Ask us a question about the project."
title: "[QUESTION] <title>"
labels: ["question"]

body:

  - type: markdown
    id: introduction
    attributes:
      value: |
        Thank you for your interest in this project. Please keep the following in mind when asking your question.
        
        - This project is provided for free and help is provided on a volunteer basis. Responses are not immediate.
        - Include all relevant information with your question.
        - Do **NOT** ask for ETAs or status updates. Things will be released when they are ready.

  - type: textarea
    id: feedback_description
    attributes:
      label: "Question"
      description: "What is your question?"
    validations:
      required: true
